accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    # auth views
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),

    # watchlist views
    path('analysis/', views.analysis, name='analysis'),
    path('get_watchlist/', views.get_watchlist, name='get_watchlist'),
    path('add_to_watchlist/', views.add_to_watchlist, name='add_to_watchlist'),
    path('remove_from_watchlist/', views.remove_from_watchlist, name='remove_from_watchlist'),

    # drawing views
    path('get_drawing/', views.get_drawing, name='get_drawing'),
    path('add_drawing/', views.add_drawing, name='add_drawing'),
    path('remove_drawing/', views.remove_drawing, name='remove_drawing'),
]

dashboard/urls.py
from django.urls import path
from .import views

app_name = "dashboard"
urlpatterns = [
    path('', views.index, name="home"),
    path('stock/', views.stock_data, name="get_stock_data"),
    path('all_stocks/', views.all_stocks, name="all_stocks"),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),
]

stock_exchange/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('dashboard.urls', namespace="dashboard")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

stocks/urls.py
from django.urls import path
from .import views

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kara Borsa - {% block title %}BASE TITLE{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style3.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="icon" type="image/x-icon" href="{% static 'img/logo2.png' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <script src="https://unpkg.com/scrollreveal"></script>
</head>
<body>
    <!-- Top Navigation -->
    <div class="navbar">
        <a href="#"><img src="{% static 'img/logo2.png' %}" alt="Borsa Takibi Logo" class="logo"></a>
        <div class="nav-links">
            <a href="{% url 'dashboard:home' %}">Ana Sayfa</a>
        
            <a href="{% url 'dashboard:home' %}">Hisseler</a>
            <a href="{% url 'accounts:analysis' %}">Analizler</a>
            <a href="{% url 'dashboard:about' %}">Hakkımızda</a>
           
        </div>
        <div class="nav-buttons">
            {% if request.user.is_authenticated %}
                <a href="{% url 'accounts:logout' %}" class="btn">Logout</a>
            {% else %}
                <a href="{% url 'accounts:login' %}" class="btn">Login</a>
                <a href="{% url 'accounts:register' %}" class="btn">Sign Up</a>
            {% endif %}
        </div>
    </div>
    
    <section id="anasayfa">
        {% block content %}
        
        {% endblock content %}
    </section>

    
    
    <!-- Footer Section -->
    <section id="hakkimizda">
        <footer>
            <div class="footer-container">
                <div class="about group">
                    <h2>BLACK BORSA</h2>
                    <p>Stock Market</p>
                </div>
                <div class="info group">
                    <h3>More</h3>
                    <ul>
                        <li><a href="#canli-borsa">Canlı Borsa</a></li>
                        <li><a href="#services">Services</a></li>
                        <li><a href="#portfolio">Portfolio</a></li>
                        <li><a href="#contact">Contact</a></li>
                    </ul>
                </div>
                <div class="follow group">
                    <h3>Follow</h3>
                    <ul>
                        <li><a href=""><i class="fab fa-instagram"></i></a></li>
                        <li><a href=""><i class="fab fa-linkedin"></i></a></li>
                        <li><a href=""><i class="fab fa-github"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="footer-copyright group">
                <p> 2024 by EKİP-8 ©Tüm Hakkları Saklıdır.</p>
            </div>
        </footer>
    </section>
    <script src="{% static 'js/anasayfa.js' %}"></script>
    
</body>
</html>