dashboard/urls.py
from django.urls import path
from .import views

app_name = "dashboard"
urlpatterns = [
    path('', views.index, name="home"),
    path('stock/', views.stock_data, name="get_stock_data"),
    path('all_stocks/', views.all_stocks, name="all_stocks"),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),
]

stock_exchange/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('dashboard.urls', namespace="dashboard")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

stocks/urls.py
from django.urls import path
from .import views

dashboard/models.py
from django.db import models

# Create your models here.

stocks/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render

from django.http import JsonResponse, HttpResponse
import json
from . import utils

from accounts.utils import get_popular_stocks, get_gaining_and_losing_stocks, get_stock_data

from accounts.models import User


def index(request):  # anasayfa

    context = {}

    popular_stocks = get_popular_stocks()
    gaining_stocks, losing_stocks = get_gaining_and_losing_stocks()

    context["graph_data"] = json.dumps(get_stock_data("XU100.IS"))
    context["popular_stocks"] = popular_stocks
    context["gaining_stocks"] = gaining_stocks
    context["losing_stocks"] = losing_stocks
    
    return render(request, "index.html", context)

import json
def stock_data(request):
    context = {}
    symbol = request.GET.get("symbol")
    print(symbol)
    data_to_return = get_stock_data(symbol)
    print(data_to_return)
    context["stock_data"] = json.dumps(data_to_return)
    context["SYMBOL"] = json.dumps(symbol)
    return render(request, "stock.html", context)


def all_stocks(request):  #stock degerleri
    context = {}

    return render(request, "stocks.html", context)


    

def about(request): #hakkımızda 
    context= {
        'page_title': 'About Us',
        'content': 'This is the about page.'
    }
    return render (request,"about.html",context)

def contact(request): #iletişim
    context ={}
    return render(request,"contact.html",context)

    """"
    web serveri icin gerekli endpointler:
    genel:
    landing
    dashboard  (takip listesi)
    hakkinda
    iletisim
    
    kullanici ile alakali:
    giriş
    kayit olma
    sahip olduğu hisseleri ve para miktarini göreceği sayfa(portfoy sayfasi)

    tema(borsa) ile ilgili şeyler: 
    tüm hisselerin görüleceği yer 
    tek bir hissenin detaylarinin görüleceği bir yer
    alim satim ve teknik analizin yapilacaği sayfa yada pop-up
    """

stocks/views.py
from django.http.response import HttpResponse
from django.shortcuts import render

# Create your views here.

dashboard/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h2>BIST 50 Endeksi</h2>
        <!-- Arama Çubuğu -->
        <div class="search-container">
            <form action="#" method="GET">
                <input type="text" id="search-bar" name="arama" placeholder="Hisse ara...">
                <button type="submit">Ara</button>
            </form>
        </div>

        <!-- BIST 100 Endeksi Grafik -->
        <canvas id="bist-grafik" width="700" height="350" style="display: block; margin: auto;"></canvas>

        <script>
            const ctx = document.getElementById('bist-grafik');
            const graphData = JSON.parse('{{ graph_data|safe }}');
            const _labels = [];
            const _data = [];
            graphData.forEach(sd => {
                console.log(sd);
                _labels.push(sd.date);
                _data.push(sd.close);
            });
            new Chart(ctx, {
                type: 'line',
                data: {
                    labels: _labels,
                    datasets: [{
                        label: 'XU100',
                        backgroundColor: "#85BB65",
                        borderColor: "#000000",
                        borderWidth: 2,
                        data: _data,
                    }]
                },
                options: {
                    layout: {
                        padding: {
                            left: 10,
                            right: 10,
                            top: 10,
                            bottom: 10
                        }
                    },
                    scales: {
                        y: {
                            beginAtZero: true
                        }
                    }
                }
            });

            document.getElementById('search-form').addEventListener('submit', function(event) {
                event.preventDefault(); // Sayfanın yenilenmesini önler

                const input = document.getElementById('search-bar').value.toLowerCase(); // Arama kutusundan değeri alır
                const rows = document.querySelectorAll('#dinamik-tablo tbody tr'); // Tablodaki tüm satırları seçer

                const searchList = document.getElementById('search-list'); // Arama sonuçlarını gösterecek liste

                // Temizleme önceki arama sonuçlarını temizler
                searchList.innerHTML = '';

                rows.forEach(row => {
                    const symbol = row.cells[0].textContent.toLowerCase(); // Her satırın ilk sütunundaki sembolü alır
                    if (symbol.includes(input)) { // Girilen değerle sembol karşılaştırması yapar
                        row.style.display = ''; // Eşleşen satırı görünür yapar

                        // Eşleşen hisse sembolünü arama sonuçları listesine ekler
                        const li = document.createElement('li');
                        li.textContent = symbol;
                        searchList.appendChild(li);
                    } else {
                        row.style.display = 'none'; // Eşleşmeyen satırı gizler
                    }
                });
            });
        </script>


        <!-- Yükselen ve Düşen Hisseler Tablosu -->
        <div id="hisseler-tablosu">
            <h3>Popüler Hisseler</h3>
            <table id="yükselen-hisseler-tablosu">
                <thead>
                    <tr>
                        <th>SEMBOL</th>
                        <th>SON</th>
                        <th>ALIŞ</th>
                        <th>SATIŞ</th>
                        <th>%G</th>
                    </tr>
                </thead>
                <tbody id="popular-stocks">
                    {% for popular_stock in popular_stocks %}
                    <tr onclick="go_to_stock_page('{{ popular_stock.SYMBOL|escapejs }}')">
                        <td>
                            {{ popular_stock.SYMBOL }}
                        </td>
                        <td>
                            {{ popular_stock.CLOSE }}
                        </td>
                        <td>
                            {{ popular_stock.BUY }}
                        </td>
                        <td>
                            {{ popular_stock.SELL }}
                        </td>
                        <td>
                            {{ popular_stock.CHANGE|floatformat:1 }}
                        </td>
                    </tr>

                    {% endfor %}
                    <!-- JavaScript ile dinamik olarak doldurulacak -->
                </tbody>
            </table>
            <h3>Yükselen Hisseler</h3>
            <table id="yükselen-hisseler-tablosu">
                <thead>
                    <tr>
                        <th>SEMBOL</th>
                        <th>SON</th>
                        <th>ALIŞ</th>
                        <th>SATIŞ</th>
                        <th>%G</th>
                    </tr>
                </thead>
                <tbody id="gaining-stocks">
                    {% for gaining_stock in gaining_stocks %}
                    <tr onclick="go_to_stock_page('{{ gaining_stock.SYMBOL|escapejs }}')">
                        <td>
                            {{ gaining_stock.SYMBOL }}
                        </td>
                        <td>
                            {{ gaining_stock.CLOSE }}
                        </td>
                        <td>
                            {{ gaining_stock.BUY }}
                        </td>
                        <td>
                            {{ gaining_stock.SELL }}
                        </td>
                        <td>
                            {{ gaining_stock.CHANGE|floatformat:1 }}
                        </td>
                    </tr>

                    {% endfor %}
                    <!-- JavaScript ile dinamik olarak doldurulacak -->
                </tbody>
            </table>
            <h3>Düşen Hisseler</h3>
            <table id="düşen-hisseler-tablosu">
                <thead>
                    <tr>
                        <th>SEMBOL</th>
                        <th>SON</th>
                        <th>ALIŞ</th>
                        <th>SATIŞ</th>
                        <th>%G</th>
                    </tr>
                </thead>
                <tbody id="losing-stocks">
                    {% for losing_stock in losing_stocks %}
                    <tr onclick="go_to_stock_page('{{ losing_stock.SYMBOL|escapejs }}')">
                        <td>
                            {{ losing_stock.SYMBOL }}
                        </td>
                        <td>
                            {{ losing_stock.CLOSE }}
                        </td>
                        <td>
                            {{ losing_stock.BUY }}
                        </td>
                        <td>
                            {{ losing_stock.SELL }}
                        </td>
                        <td>
                            {{ losing_stock.CHANGE|floatformat:1 }}
                        </td>
                    </tr>

                    {% endfor %}
                    <!-- JavaScript ile dinamik olarak doldurulacak -->
                </tbody>
            </table>
        </div>


<script>
    const popularStocksWrapper = document.getElementById("popular-stocks");
    const popularStocks = JSON.parse("{{ popular_stocks }}");
    console.log(popularStocks);
    popularStocks.forEach(stock => {
        const td = document.createElement("td");
        td.innerHTML = stock.SYMBOL;
        popularStocksWrapper.append(td);
    });
</script>
<script>
    function go_to_stock_page(stock) {
        window.location = "{% url 'dashboard:get_stock_data' %}?symbol=" + stock
    }
</script>

{% endblock content %}

dashboard/templates/stock.html
{% extends 'base.html' %}


{% block content %}
<canvas id="grafik" width="700" height="350" style="display: block; margin: auto;"></canvas>

<script>
    const ctx = document.getElementById('grafik');
    const stockData = JSON.parse('{{ stock_data|safe }}');
    console.log(stockData);
    const labels = [];
    const data = [];

    stockData.forEach(sd => {
        console.log(sd);
        labels.push(sd.date);
        data.push(sd.close);
    });
    new Chart(ctx, {
        type: 'line',
        data: {
            labels: labels,
            datasets: [{
                label: '{{ SYMBOL|safe }}',
                backgroundColor: "#85BB65",
                borderColor: "#000000",
                borderWidth: 2,
                data: data,
            }]
        },
        options: {
            layout: {
                padding: {
                    left: 10,
                    right: 10,
                    top: 10,
                    bottom: 10
                }
            },
            scales: {
                y: {
                    beginAtZero: false
                }
            }
        }
    });
</script>

{% endblock content %}
